default:
  image: gradle:7.6-jdk17
stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - ./gradlew clean build

unit-test-job:
  stage: test
  script:
    - ./gradlew test

spotless-job:
  stage: test
  script:
    - ./gradlew spotlessCheck

deploy-staging-job:
  image: "null"
  stage: deploy
  environment: staging
  script:
    - echo "Simulating deployment of application to staging..."
    - echo "Simulation of application deployment successful."
